import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("/login", "routes/login.tsx"),
  route("/forgot-password", "routes/forgot-password.tsx"),
  route("/register", "routes/register.tsx"),
  route("/dashboard", "routes/dashboard.tsx"),
  route("/upload", "routes/upload.tsx"),
  route("/history", "routes/history.tsx"),
  route("/profile", "routes/profile.tsx"),
  route("/interview", "routes/interview.tsx"),
  route("/cover-letter", "routes/cover-letter.tsx"),
  route("/resume-builder", "routes/resume-builder.tsx"),
  route("/salary", "routes/salary.tsx"),
  route("/linkedin", "routes/linkedin.tsx"),
  route("/roast", "routes/roast.tsx"),
  route("/mock-interview", "routes/mock-interview.tsx"),
  route("/skill-gap", "routes/skill-gap.tsx"),
  route("/job-tracker", "routes/job-tracker.tsx"),
  route("/campus", "routes/campus.tsx"),
  route("/roadmap", "routes/roadmap.tsx"),
  route("/leaderboard", "routes/leaderboard.tsx"),
  route("/dsa", "routes/dsa.tsx"),
  route("/company-research", "routes/company-research.tsx"),
  route("/referral", "routes/referral.tsx"),
  route("/career-guide", "routes/career-guide.tsx"),
  route("/free-resources", "routes/free-resources.tsx"),
  route("/wellness", "routes/wellness.tsx"),
  route("/linkedin-builder", "routes/linkedin-builder.tsx"),
  route("/hackathons", "routes/hackathons.tsx"),
  route("/freelancing", "routes/freelancing.tsx"),
  route("/github-optimizer", "routes/github-optimizer.tsx"),
  route("/certifications", "routes/certifications.tsx"),
  route("/templates", "routes/templates.tsx"),
  route("/jobs", "routes/jobs.tsx"),
] satisfies RouteConfig;
